export const LANG_ENGLESKI_NAME = 'engleski';


export const LANG_ENGLESKI_TRANS = {
    'ENGLISH': ' English',
    'SR_LATINICA': 'Latin',
    'SR_CIRILICA': 'Cyrillic',
    'HomePage': 'HomePage',
    'Employees': 'Employees',
    'Informations': 'Informations',
    'Bachelor': 'Bachelor',
    'Istrazivanja':'Research',
    'RTI': 'The Department of Computer Science and Information Technology',
    'SI': 'Software engineering',
    'OO': 'Another Departments',
    'Another Departments': 'Another Departments',
    'Mastrer': 'Master',
    'Projects': 'Projects',
    'Science': 'Science',
    'Contact': 'Contact',
    'About Katedra': 'About department',
    "Student sa datim korisnickim imenom vec postoji": "Username already in use",
    "Index vec postoji": "Index already in use",
    "Prazna polja": "Празна поља",
    "Index nije u dobrom formatu": "Index format not valid",
    "Student uspesno dodat": "Student succesfully added",
    "Registracija studenta": "Student Registration",
    "Lista zaposlenih": "Employees list",
    'Detaljnije': "Read more",
    "redovni profesor": "full professor",
    "vandredni profesor": "associate Professor",
    "docent": "assistant Professor",
    "asistent": "assistant",
    "saradnik u nastavi": "teaching associate",
    "istrazivac": "explorer",
    "laboratorijski inzenjer": "laboratory engineer",
    "laboratorijski tehnicar": "laboratory technician",
    "Sva obavestenja": "All information",
    "Sifra": "Subject id",
    "Ime": "Subject Name",
    "Semestar": "Semester",
    "Projekti koje mozete raditi": "Open projects",
    "Projekti koje su radili nasi zaposleni": "Done projects",
    "Sef katedre": "Head of the Department",
    "Sekretar": "Secretary",
    "Adresa": "Adress",
    'AdresaKatedre': 'Bulevar Kralja Aleksandra 73, 11100 Beograd',
    "Nema predmeta u ovom semestru": "No subjects in this semester",
    'Procitaj vise': 'Read more',
    "Ucestvovali": "Participate",
    "Uspesno registrovan korisnik sa korisnickim imenom: ": "User sussesfult added, with username: ",
    'About RTI text': "The Department of Computer Science and Information Technology provides education, research and projects in the area of computer hardware, software and networks."
}