export const LANG_SR_CIR_NAME = 'srpski_cirilica';


export const LANG_SR_CIR_TRANS = {
    'ENGLISH': ' Енглески',
    'SR_LATINICA': 'Латиница',
    'SR_CIRILICA': 'Ћирилица',
    'HomePage': 'Почетна',
    'Employees': 'Запослени',
    'Informations': 'Обавештења',
    'Istrazivanja':"Истраживања",
    'Bachelor': 'Основне студије',
    'RTI': 'Одсек за рачунарску технику и информатику',
    'SI': 'Одсек за софтверско инжењерство',
    'OO': 'Остали одсеци',
    'Another Departments': 'Остали одсеци',
    'Mastrer': 'Мастер студије',
    'Projects': 'Пројекти',
    'Science': 'Наука',
    'Contact': 'Контакт',
    'Language': 'Језик',
    "Sign Up": "Региструј се",
    "Login": "Пријави се",
    'About Katedra': 'О катедри',
    "Username": "Корисничко име",
    "First name": "Име",
    "Last name": "Презиме",
    "Index": "Индекс",
    "Password": "Шифра",
    "Study type": "Тип студија",
    "Register": "Региструј се",
    "baschelor": "Основне студије",
    'master': "Мастер студије",
    "phd": "Докторске студије",
    "Student sa datim korisnickim imenom vec postoji": "Студент са датим корисничким именом већ посотоји",
    "Index vec postoji": "Индекс већ постоји",
    "Prazna polja": "Празна поља",
    "Index nije u dobrom formatu": "Индекс није у добром формату",
    "Student uspesno dodat": "Студент успешно додат",
    "Registracija studenta": "Регистрација студената",
    "Lista zaposlenih": "Листа запослених",
    'Detaljnije': "Детаљније",
    "redovni profesor": "редовни професор",
    "vandredni profesor": "ванредни професор",
    "docent": "доцент",
    "asistent": "асистент",
    "saradnik u nastavi": "сарадник у настави",
    "istrazivac": "истраживач",
    "laboratorijski inzenjer": "лабораторијски инжењер",
    "laboratorijski tehnicar": "лабораторијски техничар",
    "Sifra": " Шифра",
    "Ime": "Име предмета",
    "Semestar": "Семестар",
    "Nema predmeta u ovom semestru": "Нема предмета у овом семестру",
    "Projekti koje mozete raditi": "Пројекти које можете радити",
    "Projekti koje su radili nasi zaposleni": "Пројекти које су радили наши запослени",
    "Sef katedre": "Шеф катедре",
    "Sekretar": "Секретар",
    "Adresa": "Адреса",
    "Uspesno registrovan korisnik sa korisnickim imenom: ": "Успешно регистрован корисник са корисничим именом: ",
    'AdresaKatedre': 'Булевар краља Александра 73, 11100 Београд',
    "Find More": "Прочитај више",
    'Procitaj vise': 'Прочитај више',
    "Ucestvovali": "Учествовали",
    'About RTI text': "Катедра за рачунарску технику и информатику се бави едукацијом, научно-истраживачким и пројектантским радом у области рачунарског хардвера, софтвера и рачунарских мрежа."
}